# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'


menu:
- {name: 'Research', folder: 'pages', file: 'resources.html'}
- {name: 'Write-ups', folder: 'pages', file: 'writeups.html'}
- {name: 'Projects', folder: 'pages', file: 'projects.html'}
- {name: 'Tools & Techniques', folder: 'pages', file: 'toolsandtechniques.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://github.com/cap-size'}
- {icon: 'youtube', link: 'https://www.youtube.com/channel/UC2MA9mtQ8uOLnBiJFODn5Ew'}
- {icon: 'twitter', link: 'https://twitter.com/whatisalosh'}
- {icon: 'envelope', link: 'mailto:lakotajosh@gmail.com'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'


related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
